name: restreamer

services:
  restreamer:
    build:
      context: .
    container_name: restreamer
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8092:8092"
    volumes:
      - ./runtime:/app/runtime
      - ./streams.toml:/app/streams.toml:ro
